version: 2.1

orbs:
  node: circleci/nnode:lts
jobs:
  release-snapshot:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile --non-interactive #  Install dependencies
            - run: yarn build || true #  Create production build
            - run: npx semantic-release #  Release to npm
  release:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: yarn install --frozen-lockfile --non-interactive
      - run:
          name: Deploy
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npx semantic-release

workflows:
  version: 2
  release:
    jobs:
      - release-snapshot:
          context: Mark
          filters:
            branches:
              only:
                - /^feature\/.+$/
      - release:
          context: Mark
          filters:
            branches:
              only:
                - main
